"""create food category map table

Revision ID: 0f34373dfc64
Revises: 426b6952c0bc
Create Date: 2026-09-04 10:26:32.148027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f34373dfc64'
down_revision: Union[str, Sequence[str], None] = '426b6952c0bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_category_map',
    sa.Column('food_id', sa.BigInteger(), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['food_categories.id'], ),
    sa.ForeignKeyConstraint(['food_id'], ['foods.id']),
    sa.PrimaryKeyConstraint('food_id', 'category_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_category_map')
    # ### end Alembic commands ###
