"""create favorite restaurants table

Revision ID: cdef1fec155f
Revises: 0f34373dfc64
Create Date: 2026-09-04 11:36:42.244765

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cdef1fec155f'
down_revision: Union[str, Sequence[str], None] = '0f34373dfc64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite_restaurants',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('restaurant_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'restaurant_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorite_restaurants')
    # ### end Alembic commands ###
