"""initial migration

Revision ID: cf7ca65d38be
Revises: 
Create Date: 2026-09-02 10:46:11.119252

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'cf7ca65d38be'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
