"""create restaurants table

Revision ID: d7f5400f3d36
Revises: 17663cc47e95
Create Date: 2026-09-02 20:19:20.060796

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'd7f5400f3d36'
down_revision: str | Sequence[str] | None = '17663cc47e95'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
