from enum import Enum

class CancellationReason(str, Enum):
    CHANGED_MIND = "CHANGED_MIND"
    TOO_LONG_TO_DELIVER = "TOO_LONG_TO_DELIVER"
    ORDERED_BY_MISTAKE = "ORDERED_BY_MISTAKE"
    FOUND_BETTER_OPTION = "FOUND_BETTER_OPTION"
    RESTAURANT_TOO_FAR = "RESTAURANT_TOO_FAR"
    OTHER = "OTHER"